version: 2
jobs:
   build:
     docker:
       - image: circleci/postgres:9.2.20
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
       - checkout
       - run: echo "Hello world Test"
